import { Component } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-rxjs-demo',
  templateUrl: './rxjs-demo.component.html',
  styleUrls: ['./rxjs-demo.component.css']
})
export class RxjsDemoComponent {

  observableObj:Observable<string>;

  constructor()
  {
    this.observableObj = new Observable( (subscriber) => {       
            subscriber.next("Data generated by observable -- 1");                    
        }); 
  }


  buttonClick()
  {
      

      this.observableObj.subscribe(resData =>
      {
        console.log(resData);
      });

      
  }

}
