import { Component } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-rxjs-demo',
  templateUrl: './rxjs-demo.component.html',
  styleUrls: ['./rxjs-demo.component.css']
})
export class RxjsDemoComponent {

  observableObj:Observable<string>;

  constructor()
  {
    this.observableObj = new Observable( (subscriber) => {        
        setTimeout(
          () =>  {
            subscriber.next("Data generated by observable -- 1");           
          }, 3000);  // wait the process for 3 sec
        }); 
  }


  buttonClick()
  {
      console.log("Before Subscribe --- Line26");

      this.observableObj.subscribe(resData =>
      {
        console.log(resData + " --- Line 30");
      });

      console.log("After Subscribe --- Line33");
  }

}
