import { Component } from '@angular/core';
import { Observable, Subscription, from, interval, map, of } from 'rxjs';

@Component({
  selector: 'app-rxjs-demo',
  templateUrl: './rxjs-demo.component.html',
  styleUrls: ['./rxjs-demo.component.css']
})
export class RxjsDemoComponent {

  subscribe?:Subscription;
  str:string  =  "";
  observableObj:Observable<any>;

  constructor()
  {    
    this.observableObj = interval(1000);

    let observableObj:Observable<string> = new Observable( (subscriber) => {
      subscriber.next("Data generated by observable -- 1");  
  });

  
  }

  startButtonClick()
  {
    
    this.subscribe  =  this.observableObj.subscribe(item => {
        // console.log(item);
        this.str  += " ** " + item;
    });
  }

  stopButtonClick()
  {
    this.subscribe?.unsubscribe();
  }
}
